server:
  port: 9000
  servlet:
    context-path: /

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  sql:
    init:
      platform: h2

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 70244447215-jhvkbvf14skdt3jv9cscf0r3kg3303ip.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

          naver:
            client-id: VsA3zRXBWa_htpTNPr2z
            client-secret: zhGo0aPpnZ
            scope:
              - name
              - email

            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:9000/login/oauth2/code/naver

          kakao:
            client-id: 1c1ed3f04f0b65646e3a3d4c9350fb12
            client-secret: VdKmmv1euGAgtPyPxHgzm5Ogid8lldm2
            scope:
              - profile_nickname
              - account_email

            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:9000/login/oauth2/code/kakao
            client-authentication-method: POST

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

logging:
  level:
    root: info
    com.jbsapp.web: debug
